Fixed some bugs.  Sort of runs now
Getting a weird error from keras_fit though--need to debug:

plpy.SPIError: ValueError: Error when checking model input: the list of
Numpy arrays that you are passing to your model is not the size the
model expected. Expected to see 1 array(s), but instead got the
following list of 120 arrays